/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// NinjaChat contract SHA-256: bcf3aa3d26a7927cecba74a931de447808ace44b3998e140635af714c4192815
export interface paths {
    "/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BalanceResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a chat completion
         * @description OpenAI-compatible chat completions with ordered model fallbacks and provider routing policy. Pass model "@slug" to run a saved preset you own — the preset supplies models, prompt, tools, and routing; send only messages.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safely retry the same logical write without duplicate billing or execution. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChatCompletionsRequest"];
                };
            };
            responses: {
                /** @description Chat completion or SSE stream. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                        "text/event-stream": string;
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get gateway health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Measured gateway health. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate images */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safely retry the same logical write without duplicate billing or execution. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ImageGenerationRequest"];
                };
            };
            responses: {
                /** @description Generated images and unit cost. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImageGenerationResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List live models */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime catalog data, capabilities, provider rails, availability, and prices. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a live model */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime model detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicModel"];
                    };
                };
                /** @description Model not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get this OpenAPI document */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI 3.1 document. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{slug}/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a saved preset
         * @description Chat completion using a preset's saved model, routing, system prompt, and parameters. Send only your messages; pass model/models to override the preset's chain for this call. Response headers include X-Ninja-Preset and X-Ninja-Preset-Version.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safely retry the same logical write without duplicate billing or execution. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PresetChatCompletionsRequest"];
                };
            };
            responses: {
                /** @description Chat completion or SSE stream. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                        "text/event-stream": string;
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No active preset with that slug on this account. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a request trace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequestRecordResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a stateless response
         * @description OpenAI Responses-compatible text, vision, structured-output, and function-calling API. Set stream=true for typed lifecycle events.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safely retry the same logical write without duplicate billing or execution. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResponsesRequest"];
                };
            };
            responses: {
                /** @description Completed response or SSE stream. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResponseObject"];
                        "text/event-stream": string;
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search the web */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safely retry the same logical write without duplicate billing or execution. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SearchRequest"];
                };
            };
            responses: {
                /** @description Search results and optional answer. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get usage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a video job
         * @description Submit an async video job. Poll GET /videos/{id}, or register a signed webhook (POST /webhooks or https://www.ninjachat.ai/developers/keys#webhooks) for video.completed / video.failed.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safely retry the same logical write without duplicate billing or execution. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VideoCreateRequest"];
                };
            };
            responses: {
                /** @description Queued video job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoCreateResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a video job
         * @description Poll job status until completed or failed. Prefer a webhook if you do not want to poll.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Video job status or completed URL. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoStatusResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Video job not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhooks
         * @description List HTTPS endpoints registered for video completion and spend-alert callbacks. Console: https://www.ninjachat.ai/developers/keys#webhooks
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registered webhook endpoints. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookListResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a webhook
         * @description Register an HTTPS URL. NinjaChat POSTs signed JSON for video.completed (includes video_url), video.failed (refunded), budget.alert (50/80/100% of a spend limit), and balance.low (prepaid $5/$1) so you do not have to poll video jobs. The signing secret is returned once. Console: https://www.ninjachat.ai/developers/keys#webhooks
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WebhookCreateRequest"];
                };
            };
            responses: {
                /** @description Webhook created. The signing secret is returned once. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookCreateResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Delete a webhook */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Webhook deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDeleteResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhook deliveries
         * @description Recent delivery attempts for one endpoint, newest first.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent webhook deliveries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDeliveriesResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test webhook
         * @description Send one synthetic event immediately so you can verify signature handling before relying on live jobs.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WebhookTestRequest"];
                };
            };
            responses: {
                /** @description Immediate test delivery result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookTestResponse"];
                    };
                };
                /** @description Invalid or unsupported request parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient balance or project spend limit reached. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Gateway error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BalanceResponse: {
            balance: string;
            balance_cents: number;
            /** @enum {string} */
            currency: "usd";
            /** @enum {string} */
            object: "balance";
            request_id: string;
        };
        ChatCompletionResponse: {
            choices: {
                finish_reason: string | null;
                index: number;
                message: {
                    content: string | null;
                    /** @enum {string} */
                    role: "assistant";
                    tool_calls?: {
                        function: {
                            arguments: string;
                            name: string;
                        };
                        id: string;
                        /** @enum {string} */
                        type: "function";
                    }[];
                };
            }[];
            cost_usd: number;
            created: number;
            id: string;
            model: string;
            /** @enum {string} */
            object: "chat.completion";
            provider: string | null;
            request_id: string;
            resolved_model: string;
            routing: components["schemas"]["RoutingSummary"];
            usage: components["schemas"]["ChatUsage"];
        };
        ChatCompletionsRequest: {
            frequency_penalty?: number;
            max_completion_tokens?: number;
            messages: ({
                content: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[];
                /** @enum {string} */
                role: "developer";
            } | {
                content: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[];
                /** @enum {string} */
                role: "system";
            } | {
                content: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[];
                /** @enum {string} */
                role: "user";
            } | {
                content?: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[] | null;
                /** @enum {string} */
                role: "assistant";
                tool_calls?: {
                    function: {
                        arguments: string;
                        name: string;
                    };
                    id: string;
                    /** @enum {string} */
                    type: "function";
                }[];
            } | {
                content: string;
                /** @enum {string} */
                role: "tool";
                tool_call_id: string;
            })[];
            model?: string;
            models?: string[];
            parallel_tool_calls?: boolean;
            presence_penalty?: number;
            response_format?: {
                /** @enum {string} */
                type: "text";
            } | {
                /** @enum {string} */
                type: "json_object";
            } | {
                json_schema: {
                    description?: string;
                    name: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    /** @default true */
                    strict: boolean;
                };
                /** @enum {string} */
                type: "json_schema";
            };
            routing?: components["schemas"]["RoutingPolicy"];
            seed?: number;
            stop?: string | string[];
            /** @default false */
            stream: boolean;
            stream_options?: {
                include_usage?: boolean;
            };
            temperature?: number;
            tool_choice?: ("none" | "auto" | "required") | {
                function: {
                    name: string;
                };
                /** @enum {string} */
                type: "function";
            };
            tools?: {
                function: {
                    description?: string;
                    name: string;
                    /** @default {} */
                    parameters: {
                        [key: string]: unknown;
                    };
                    strict?: boolean;
                };
                /** @enum {string} */
                type: "function";
            }[];
            top_p?: number;
            user?: string;
        };
        ChatUsage: {
            completion_tokens: number;
            completion_tokens_details?: {
                reasoning_tokens?: number;
            };
            prompt_tokens: number;
            prompt_tokens_details?: {
                cache_creation_tokens?: number;
                cached_tokens?: number;
            };
            total_tokens: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                param?: string | null;
                type: string;
            };
        };
        ImageGenerationRequest: {
            aspect_ratio?: string;
            height?: number;
            /** Format: uri */
            image?: string;
            /**
             * @default nano-banana-2
             * @enum {string}
             */
            model: "nova-canvas" | "runway-gen4-image-turbo" | "seedream" | "recraft-v3" | "google-imagen-4" | "nano-banana" | "nano-banana-2" | "nano-banana-pro" | "flux-2-klein" | "flux-2-pro" | "flux-2-max" | "flux-2-flex" | "flux-schnell" | "flux-kontext-pro" | "flux-kontext-max" | "flux-1-pro-ultra" | "flux-1.1-pro" | "flux-1-dev" | "flux-1-fill" | "qwen-image-3" | "qwen-image-max" | "seedream-4.5" | "seedream-5-lite" | "seedream-5-pro" | "flux-2-klein-4b" | "flux-2-klein-9b" | "sdxl-turbo" | "pruna-p-image" | "wan-2.6-image" | "nano-banana-2-lite" | "bria-fibo" | "bria-3.2" | "qwen-image-edit-max" | "wan-2.7-image-edit" | "z-image-turbo" | "qwen-image-2512" | "flux-2-dev" | "stable-diffusion-3.5-large" | "qwen-image-edit-2511" | "flux-kontext-dev" | "grok-imagine" | "grok-imagine-image-2.0" | "grok-imagine-image-quality" | "gpt-image-2";
            /** @default 1 */
            n: number;
            prompt: string;
            /**
             * @default 1920x1920
             * @enum {string}
             */
            size: "1920x1920" | "2560x1440" | "1440x2560";
            width?: number;
        };
        ImageGenerationResponse: {
            cost_usd: number;
            created: number;
            data: {
                revised_prompt?: string | null;
                /** Format: uri */
                url: string;
            }[];
            model: string;
            provider: string;
            request_id: string;
            routing: {
                provider_attempts: string[];
                retries: number;
            };
            usage: {
                images_generated: number;
            };
        };
        ModelListResponse: {
            data: components["schemas"]["PublicModel"][];
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            object: "list";
            total: number;
        };
        PresetChatCompletionsRequest: {
            frequency_penalty?: number;
            max_completion_tokens?: number;
            messages: ({
                content: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[];
                /** @enum {string} */
                role: "developer";
            } | {
                content: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[];
                /** @enum {string} */
                role: "system";
            } | {
                content: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[];
                /** @enum {string} */
                role: "user";
            } | {
                content?: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "text";
                } | {
                    image_url: {
                        /** @enum {string} */
                        detail?: "auto" | "low" | "high";
                        url: string;
                    };
                    /** @enum {string} */
                    type: "image_url";
                })[] | null;
                /** @enum {string} */
                role: "assistant";
                tool_calls?: {
                    function: {
                        arguments: string;
                        name: string;
                    };
                    id: string;
                    /** @enum {string} */
                    type: "function";
                }[];
            } | {
                content: string;
                /** @enum {string} */
                role: "tool";
                tool_call_id: string;
            })[];
            model?: string;
            models?: string[];
            parallel_tool_calls?: boolean;
            presence_penalty?: number;
            response_format?: {
                /** @enum {string} */
                type: "text";
            } | {
                /** @enum {string} */
                type: "json_object";
            } | {
                json_schema: {
                    description?: string;
                    name: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    /** @default true */
                    strict: boolean;
                };
                /** @enum {string} */
                type: "json_schema";
            };
            routing?: components["schemas"]["RoutingPolicy"];
            seed?: number;
            stop?: string | string[];
            /** @default false */
            stream: boolean;
            stream_options?: {
                include_usage?: boolean;
            };
            temperature?: number;
            tool_choice?: ("none" | "auto" | "required") | {
                function: {
                    name: string;
                };
                /** @enum {string} */
                type: "function";
            };
            tools?: {
                function: {
                    description?: string;
                    name: string;
                    /** @default {} */
                    parameters: {
                        [key: string]: unknown;
                    };
                    strict?: boolean;
                };
                /** @enum {string} */
                type: "function";
            }[];
            top_p?: number;
            user?: string;
        };
        PublicModel: {
            brand: string;
            capabilities: string[];
            contextWindow?: number;
            created: number;
            description?: string;
            history?: {
                [key: string]: unknown;
            }[];
            id: string;
            maxOutputTokens?: number;
            /** @enum {string} */
            modality: "text" | "image" | "image_edit" | "video" | "audio" | "embedding" | "rerank" | "search";
            name: string;
            /** @enum {string} */
            object: "model";
            overlay?: {
                /** @enum {string} */
                dispatch: "live" | "pending";
                isOverlay: boolean;
                overrideStatus?: string;
            };
            owned_by: string;
            pricing: {
                listPerUnitUsd?: number;
                meteredCachedPromptPerToken?: number;
                meteredCacheWritePromptPerToken?: number;
                meteredCompletionPerToken?: number;
                meteredPromptPerToken?: number;
                perRequestUsd?: number;
                perUnitUsd?: number;
                promotion?: {
                    discountPercent: number;
                    /** Format: date-time */
                    endsAt: string;
                    label: string;
                    /** Format: date-time */
                    startsAt: string;
                };
                typicalRequestUsd?: number;
                /** @enum {string} */
                unit: "token" | "image" | "second" | "request";
            };
            pricingNote?: string;
            providers: {
                available: boolean;
                contextWindow?: number;
                maxOutputTokens?: number;
                performance?: {
                    medianTtftMs: number | null;
                    p50Ms: number | null;
                    p95Ms: number | null;
                    samples: number;
                    successRate: number | null;
                    thin: boolean;
                } | null;
                provider: string;
                providerDisplayName: string;
                /** @enum {string} */
                role: "primary" | "fallback" | "emergency";
                trainsOnData?: boolean;
                unsupportedCapabilities?: ("tools" | "vision" | "json_mode" | "streaming")[];
                upstreamModelId: string;
                zeroRetentionAvailable?: boolean;
            }[];
            servable: boolean;
            /** @enum {string} */
            status: "preview" | "ga" | "deprecated" | "retired";
            supportedParameters: string[];
            virtual?: boolean;
        };
        RequestRecordResponse: {
            cost_cents: number | null;
            endpoint: string | null;
            error_code: string | null;
            latency_ms: number | null;
            metered_cost_cents: number | null;
            model: string | null;
            model_requested: string | null;
            /** @enum {string} */
            object: "request";
            provider: string | null;
            request_id: string;
            retries: number | null;
            routing: {
                attempts: {
                    error_code: string | null;
                    latency_ms: number;
                    model: string;
                    /** @enum {string} */
                    outcome: "ok" | "error" | "timeout" | "aborted";
                    retry_budget_consumed: boolean;
                }[];
                considered: string[];
                excluded: {
                    model: string;
                    reason: string;
                    stage: string;
                }[];
                /** @enum {string} */
                ordering: "breaker" | "perf" | "static";
                policy: {
                    allow_fallbacks: boolean;
                    /** @enum {string} */
                    caching?: "auto";
                    /** @enum {string} */
                    data_policy: "default" | "no_training" | "zero_retention";
                    max_cost_usd?: number;
                    providers: {
                        exclude?: string[];
                        only?: string[];
                        order?: string[];
                    };
                    require_parameters: boolean;
                    /** @enum {string} */
                    source: "request" | "project" | "default";
                    /** @enum {string} */
                    strategy: "balanced" | "cost" | "latency" | "quality";
                } | null;
                requested_models: string[];
                served_by: {
                    attempt_index: number;
                    model: string;
                    provider: string | null;
                } | null;
            } | null;
            status_code: number | null;
            timestamp: string | null;
            tokens: {
                cache_write: number | null;
                cached: number | null;
                input: number | null;
                output: number | null;
                reasoning: number | null;
            };
            ttfb_ms: number | null;
        };
        ResponseObject: {
            cost_usd: number;
            created_at: number;
            error: null;
            id: string;
            incomplete_details: null;
            instructions: string | null;
            max_output_tokens: number | null;
            metadata: {
                [key: string]: string;
            };
            model: string;
            /** @enum {string} */
            object: "response";
            output: ({
                content: {
                    annotations: unknown[];
                    text: string;
                    /** @enum {string} */
                    type: "output_text";
                }[];
                id: string;
                /** @enum {string} */
                role: "assistant";
                /** @enum {string} */
                status: "completed";
                /** @enum {string} */
                type: "message";
            } | {
                arguments: string;
                call_id: string;
                id: string;
                name: string;
                /** @enum {string} */
                status: "completed";
                /** @enum {string} */
                type: "function_call";
            })[];
            output_text: string;
            parallel_tool_calls: boolean;
            previous_response_id: null;
            provider: string | null;
            request_id: string;
            routing: components["schemas"]["RoutingSummary"];
            /** @enum {string} */
            status: "completed";
            /** @enum {boolean} */
            store: false;
            usage: {
                input_tokens: number;
                input_tokens_details: {
                    cache_creation_tokens: number;
                    cached_tokens: number;
                };
                output_tokens: number;
                output_tokens_details: {
                    reasoning_tokens: number;
                };
                total_tokens: number;
            };
        };
        ResponsesRequest: {
            input: string | ({
                content: string | ({
                    text: string;
                    /** @enum {string} */
                    type: "input_text";
                } | {
                    /** @enum {string} */
                    detail?: "auto" | "low" | "high";
                    image_url: string;
                    /** @enum {string} */
                    type: "input_image";
                })[];
                /** @enum {string} */
                role: "developer" | "system" | "user" | "assistant";
                /** @enum {string} */
                type?: "message";
            } | {
                arguments: string;
                call_id: string;
                name: string;
                /** @enum {string} */
                type: "function_call";
            } | {
                call_id: string;
                output: string;
                /** @enum {string} */
                type: "function_call_output";
            })[];
            instructions?: string;
            max_output_tokens?: number;
            metadata?: {
                [key: string]: string;
            };
            model?: string;
            models?: string[];
            parallel_tool_calls?: boolean;
            routing?: components["schemas"]["RoutingPolicy"];
            /**
             * @default false
             * @enum {boolean}
             */
            store: false;
            /** @default false */
            stream: boolean;
            temperature?: number;
            text?: {
                format?: {
                    /** @enum {string} */
                    type: "text";
                } | {
                    /** @enum {string} */
                    type: "json_object";
                } | {
                    description?: string;
                    name: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    /** @default true */
                    strict: boolean;
                    /** @enum {string} */
                    type: "json_schema";
                };
            };
            tool_choice?: ("none" | "auto" | "required") | {
                name: string;
                /** @enum {string} */
                type: "function";
            };
            tools?: {
                description?: string;
                name: string;
                /** @default {} */
                parameters: {
                    [key: string]: unknown;
                };
                strict?: boolean;
                /** @enum {string} */
                type: "function";
            }[];
            top_p?: number;
            user?: string;
        };
        RoutingPolicy: {
            /** @default true */
            allow_fallbacks: boolean;
            /** @enum {string} */
            caching?: "auto";
            /**
             * @default default
             * @enum {string}
             */
            data_policy: "default" | "no_training" | "zero_retention";
            max_cost_usd?: number;
            providers?: {
                exclude?: string[];
                only?: string[];
                order?: string[];
            };
            /** @default true */
            require_parameters: boolean;
            /** @enum {string} */
            strategy?: "balanced" | "cost" | "latency" | "quality";
        };
        RoutingSummary: {
            /** @enum {string} */
            caching?: "auto";
            /** @enum {string} */
            data_policy: "default" | "no_training" | "zero_retention";
            fallbacks_allowed: boolean;
            provider: string | null;
            requested_models: string[];
            resolved_model: string;
            /** @enum {string} */
            source?: "request" | "project" | "default";
            /** @enum {string} */
            strategy: "balanced" | "cost" | "latency" | "quality";
        };
        SearchRequest: {
            /**
             * @default web
             * @enum {string}
             */
            group: "web" | "news";
            /** @default true */
            include_answer: boolean;
            /** @default false */
            include_images: boolean;
            /** @default 10 */
            max_results: number;
            query: string;
            /**
             * @default basic
             * @enum {string}
             */
            search_depth: "basic" | "advanced";
            /**
             * @default general
             * @enum {string}
             */
            topic: "general" | "news" | "finance";
        };
        SearchResponse: {
            answer: string | null;
            cost_usd: number;
            follow_up_questions: string[];
            images?: {
                description: string | null;
                url: string;
            }[];
            /** @enum {string} */
            object: "search.results";
            provider: string;
            query: string;
            request_id: string;
            sources: {
                content: string;
                published_date: string | null;
                title: string;
                url: string;
            }[];
        };
        UsageResponse: {
            by_endpoint: {
                endpoint: string | null;
                requests: number;
            }[];
            by_model: {
                avg_latency_ms: number;
                cost_cents: number;
                model: string;
                requests: number;
            }[];
            daily: {
                cost_cents: number;
                date: string;
                requests: number;
            }[];
            /** @enum {string} */
            period: "1d" | "7d" | "30d";
            request_id: string;
            total_cost: string;
            total_cost_cents: number;
            total_requests: number;
        };
        VideoCreateRequest: {
            /**
             * @default 16:9
             * @enum {string}
             */
            aspect_ratio: "16:9" | "9:16";
            /** @default 8 */
            duration: number;
            /** Format: uri */
            end_image_url?: string;
            /** @default false */
            generate_audio: boolean;
            /** Format: uri */
            image_url?: string;
            /**
             * @default veo-3.1-fast
             * @enum {string}
             */
            model: "nova-reel" | "runway-gen4.5" | "seedance-2" | "seedance-2.0-fast" | "seedance-2-mini" | "seedance-2.0" | "seedance-1.5-pro" | "seedance-lite" | "seedance-pro" | "grok-imagine-video" | "grok-imagine-video-1.5" | "kling-2.5-turbo" | "kling-3-pro" | "wan-2.7" | "wan-2.7-i2v" | "wan-2.7-r2v" | "wan-2.6" | "wan-2.6-i2v" | "wan-2.2-t2v-a14b" | "fast-wan-2.2" | "fast-wan-qad" | "pruna-p-video" | "pixverse-6" | "pixverse-6-i2v" | "cosmos-3-nano" | "cosmos-3-super" | "vidu-q3" | "veo-3.1" | "veo-3.1-fast" | "kling-video" | "google-veo-2" | "google-veo-3-fast";
            prompt: string;
            /** Format: uri */
            reference_audio?: string;
            reference_images?: string[];
            /** Format: uri */
            reference_video?: string;
            /** @default false */
            watermark: boolean;
        };
        VideoCreateResponse: {
            cost_usd: number;
            id: string;
            model: string;
            /** @enum {string} */
            object: "video";
            request_id: string;
            /** @enum {string} */
            status: "queued";
        };
        VideoStatusResponse: {
            error?: string;
            id: string;
            /** @enum {string} */
            object: "video";
            progress?: number;
            /** @enum {string} */
            status: "queued" | "processing" | "completed" | "failed";
            /** Format: uri */
            video_url?: string;
        };
        WebhookCreateRequest: {
            /** @default [
             *       "video.completed",
             *       "video.failed",
             *       "budget.alert",
             *       "balance.low"
             *     ] */
            events: components["schemas"]["WebhookEvent"][];
            /** Format: uri */
            url: string;
        };
        WebhookCreateResponse: {
            events: components["schemas"]["WebhookEvent"][];
            id: string;
            message: string;
            secret: string;
            /** Format: uri */
            url: string;
        };
        WebhookDeleteResponse: {
            /** @enum {boolean} */
            disabled: true;
            id: string;
        };
        WebhookDeliveriesResponse: {
            deliveries: components["schemas"]["WebhookDelivery"][];
        };
        WebhookDelivery: {
            attempts: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            delivered_at: string | null;
            endpoint_id: string | null;
            event: string;
            id: string;
            last_error: string | null;
            /** Format: date-time */
            next_attempt_at: string;
            request_id: string | null;
            /** @enum {string} */
            status: "delivered" | "retrying" | "dead" | "pending";
        };
        WebhookEndpoint: {
            /** Format: date-time */
            created_at: string;
            events: components["schemas"]["WebhookEvent"][];
            id: string;
            secret_hint: string;
            /** Format: uri */
            url: string;
        };
        /** @enum {string} */
        WebhookEvent: "video.completed" | "video.failed" | "budget.alert" | "balance.low";
        WebhookListResponse: {
            endpoints: components["schemas"]["WebhookEndpoint"][];
        };
        WebhookTestRequest: {
            endpoint_id: string;
        };
        WebhookTestResponse: {
            delivered: boolean;
            detail: string | null;
        };
    };
    responses: never;
    parameters: {
        /** @description Safely retry the same logical write without duplicate billing or execution. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
